# Feature Engineering

## Objective

Create meaningful business features that improve demand prediction and pricing analysis.

The engineered features will be used in the machine learning model and price elasticity analysis.

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/data/retail_price.csv")

## Revenue

Revenue represents the total income generated from product sales.

Formula:

Revenue = Quantity Sold × Unit Price

In [3]:
df["revenue"] = df["qty"] * df["unit_price"]

df[["qty","unit_price","revenue"]].head()

   qty  unit_price  revenue
0    1       45.95    45.95
1    3       45.95   137.85
2    6       45.95   275.70
3    4       45.95   183.80
4    2       45.95    91.90

## Average Competitor Price

Average competitor price provides an overall market price for comparison.

In [4]:
df["avg_comp_price"] = (
    df["comp_1"] +
    df["comp_2"] +
    df["comp_3"]
) / 3

df[["comp_1","comp_2","comp_3","avg_comp_price"]].head()

   comp_1      comp_2  comp_3  avg_comp_price
0    89.9  215.000000   45.95      116.950000
1    89.9  209.000000   45.95      114.950000
2    89.9  205.000000   45.95      113.616667
3    89.9  199.509804   45.95      111.786601
4    89.9  163.398710   45.95       99.749570

## Price Difference

Price Difference measures how much higher or lower our price is compared to competitors.

In [5]:
df["price_difference"] = (
    df["unit_price"] -
    df["avg_comp_price"]
)

df[["unit_price","avg_comp_price","price_difference"]].head()

   unit_price  avg_comp_price  price_difference
0       45.95      116.950000        -71.000000
1       45.95      114.950000        -69.000000
2       45.95      113.616667        -67.666667
3       45.95      111.786601        -65.836601
4       45.95       99.749570        -53.799570

In [6]:
df["price_ratio"] = (
    df["unit_price"] /
    df["avg_comp_price"]
)

df[["unit_price","avg_comp_price","price_ratio"]].head()

   unit_price  avg_comp_price  price_ratio
0       45.95      116.950000     0.392903
1       45.95      114.950000     0.399739
2       45.95      113.616667     0.404430
3       45.95      111.786601     0.411051
4       45.95       99.749570     0.460654

In [7]:
df["freight_percentage"] = (
    df["freight_price"] /
    df["unit_price"]
) * 100

df[["freight_price","unit_price","freight_percentage"]].head()

   freight_price  unit_price  freight_percentage
0      15.100000       45.95           32.861806
1      12.933333       45.95           28.146536
2      14.840000       45.95           32.295974
3      14.287500       45.95           31.093580
4      15.100000       45.95           32.861806

In [8]:
df["revenue_per_customer"] = (
    df["revenue"] /
    df["customers"]
)

df[["revenue","customers","revenue_per_customer"]].head()

   revenue  customers  revenue_per_customer
0    45.95         57              0.806140
1   137.85         61              2.259836
2   275.70        123              2.241463
3   183.80         90              2.042222
4    91.90         54              1.701852

In [9]:
df.head()

,product_id,product_category_name,month_year,qty,total_price,freight_price,unit_price,product_name_lenght,product_description_lenght,product_photos_qty,...,comp_3,ps3,fp3,lag_price,revenue,avg_comp_price,price_difference,price_ratio,freight_percentage,revenue_per_customer
0,bed1,bed_bath_table,01-05-2017,1,45.95,15.100000,45.95,39,161,2,...,45.95,4.0,15.100000,45.90,45.95,116.950000,-71.000000,0.392903,32.861806,0.806140
1,bed1,bed_bath_table,01-06-2017,3,137.85,12.933333,45.95,39,161,2,...,45.95,4.0,12.933333,45.95,137.85,114.950000,-69.000000,0.399739,28.146536,2.259836
2,bed1,bed_bath_table,01-07-2017,6,275.70,14.840000,45.95,39,161,2,...,45.95,4.0,14.840000,45.95,275.70,113.616667,-67.666667,0.404430,32.295974,2.241463
3,bed1,bed_bath_table,01-08-2017,4,183.80,14.287500,45.95,39,161,2,...,45.95,4.0,14.287500,45.95,183.80,111.786601,-65.836601,0.411051,31.093580,2.042222
4,bed1,bed_bath_table,01-09-2017,2,91.90,15.100000,45.95,39,161,2,...,45.95,4.0,15.100000,45.95,91.90,99.749570,-53.799570,0.460654,32.861806,1.701852

In [10]:
df.to_csv("../data/retail_price_feature_engineered.csv", index=False)